import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1782015647067 implements MigrationInterface {
    name = 'Init1782015647067'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "media_relations" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "media_id" integer NOT NULL, "entity_type" character varying NOT NULL, "entity_id" integer NOT NULL, "is_cover" boolean NOT NULL DEFAULT false, "sort_order" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_0bbdf1c0f865e962a006bb84dc2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "media" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "type" character varying NOT NULL, "original_name" character varying NOT NULL, "mime_type" character varying NOT NULL, "size" bigint NOT NULL, "file_name" character varying NOT NULL, "path" character varying NOT NULL, "extension" character varying NOT NULL, CONSTRAINT "PK_f4e0fcac36e050de337b670d8bd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "permissions" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "key" character varying NOT NULL, "description" character varying, CONSTRAINT "UQ_017943867ed5ceef9c03edd9745" UNIQUE ("key"), CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "name" character varying NOT NULL, "slug" character varying NOT NULL, "description" character varying, CONSTRAINT "UQ_881f72bac969d9a00a1a29e1079" UNIQUE ("slug"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('active', 'inactive', 'banned')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "profile_image_id" integer, "full_name" character varying, "username" character varying NOT NULL, "password_hash" character varying NOT NULL, "email" character varying, "email_verified_at" TIMESTAMP, "phone" character varying, "status" "public"."users_status_enum" NOT NULL DEFAULT 'active', "last_login_at" TIMESTAMP, CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "users_verified_email_unique" ON "users"  ("email") WHERE "email_verified_at" IS NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."blocked_ips_reason_enum" AS ENUM('manual_block', 'brute_force', 'too_many_requests', 'security_policy')`);
        await queryRunner.query(`CREATE TABLE "blocked_ips" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "ip_address" character varying NOT NULL, "reason" "public"."blocked_ips_reason_enum", "expires_at" TIMESTAMP, CONSTRAINT "PK_e86c3986ac081ad24d5443bb6c5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."otp_codes_purpose_enum" AS ENUM('verify_email', 'reset_password', 'recover_username')`);
        await queryRunner.query(`CREATE TABLE "otp_codes" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "email" character varying NOT NULL, "code_hash" character varying NOT NULL, "purpose" "public"."otp_codes_purpose_enum" NOT NULL, "expires_at" TIMESTAMP NOT NULL, "used_at" TIMESTAMP, "attempts_count" integer NOT NULL DEFAULT '0', "request_ip" character varying, CONSTRAINT "PK_9d0487965ac1837d57fec4d6a26" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "user_id" integer, "action" character varying NOT NULL, "entity_type" character varying NOT NULL, "entity_id" integer NOT NULL, "changes" jsonb, "ip_address" character varying, "user_agent" character varying, CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cee5459245f652b75eb2759b4c" ON "audit_logs"  ("action") `);
        await queryRunner.query(`CREATE INDEX "IDX_7421efc125d95e413657efa3c6" ON "audit_logs"  ("entity_type", "entity_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bd2726fd31b35443f2245b93ba" ON "audit_logs"  ("user_id") `);
        await queryRunner.query(`CREATE TABLE "security_logs" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "user_id" integer, "event" character varying NOT NULL, "ip_address" character varying NOT NULL, "user_agent" character varying NOT NULL, CONSTRAINT "PK_48ce9a9a3215af82611525ce08b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3fc41b4fda367506672e9030ad" ON "security_logs"  ("user_id") `);
        await queryRunner.query(`CREATE TABLE "system_logs" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "level" character varying NOT NULL, "message" character varying NOT NULL, "context" jsonb, CONSTRAINT "PK_56861c4b9d16aa90259f4ce0a2c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "categories" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "title" character varying NOT NULL, "slug" character varying NOT NULL, "parent_id" integer, CONSTRAINT "UQ_420d9f679d41281f282f5bc7d09" UNIQUE ("slug"), CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tags" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "title" character varying NOT NULL, "slug" character varying NOT NULL, CONSTRAINT "UQ_b3aa10c29ea4e61a830362bd25a" UNIQUE ("slug"), CONSTRAINT "PK_e7dc17249a1148a1970748eda99" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."comments_status_enum" AS ENUM('pending', 'approved', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "comments" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "content_id" integer NOT NULL, "parent_id" integer, "user_id" integer NOT NULL, "body" text NOT NULL, "status" "public"."comments_status_enum" NOT NULL DEFAULT 'pending', CONSTRAINT "PK_8bf68bc960f2b69e818bdb90dcb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ratings" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "content_id" integer NOT NULL, "user_id" integer NOT NULL, "value" smallint NOT NULL, CONSTRAINT "UQ_1e3ad52ccf56e0ae686e06e13ce" UNIQUE ("content_id", "user_id"), CONSTRAINT "CHK_9cf0acac1b57c4eefb4bd39dab" CHECK ("value" BETWEEN 1 AND 5), CONSTRAINT "PK_0f31425b073219379545ad68ed9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."content_reports_status_enum" AS ENUM('pending', 'reviewed', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "content_reports" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "content_id" integer NOT NULL, "user_id" integer NOT NULL, "subject" character varying NOT NULL, "description" text, "status" "public"."content_reports_status_enum" NOT NULL DEFAULT 'pending', CONSTRAINT "PK_6c59a68146cdde8de564ee649c1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."contents_status_enum" AS ENUM('draft', 'published', 'archived')`);
        await queryRunner.query(`CREATE TABLE "contents" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "type" character varying NOT NULL, "title" character varying NOT NULL, "slug" character varying NOT NULL, "summary" character varying, "body" text, "cover_id" integer, "author_id" integer NOT NULL, "status" "public"."contents_status_enum" NOT NULL DEFAULT 'draft', "is_featured" boolean NOT NULL DEFAULT false, "published_at" TIMESTAMP, "views_count" integer NOT NULL DEFAULT '0', CONSTRAINT "UQ_8a8cf14dab55b4ebcd93bb536a1" UNIQUE ("slug"), CONSTRAINT "PK_b7c504072e537532d7080c54fac" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."form_fields_type_enum" AS ENUM('text', 'textarea', 'number', 'email', 'phone', 'select', 'radio', 'checkbox', 'date', 'file')`);
        await queryRunner.query(`CREATE TABLE "form_fields" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "form_id" integer NOT NULL, "label" character varying NOT NULL, "key" character varying NOT NULL, "type" "public"."form_fields_type_enum" NOT NULL, "is_required" boolean NOT NULL DEFAULT false, "description" text, "validation_rules" jsonb, "options" jsonb, "order_index" integer NOT NULL DEFAULT '0', CONSTRAINT "UQ_45772236704d0761ed24441fe1e" UNIQUE ("form_id", "key"), CONSTRAINT "PK_dc4b73290f2926c3a7d7c92d1e1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "form_permissions" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "form_id" integer NOT NULL, "role_id" integer NOT NULL, "can_view" boolean NOT NULL DEFAULT true, "can_submit" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_d32a2961957ff25fee980fbe263" UNIQUE ("form_id", "role_id"), CONSTRAINT "PK_3f483bca1d9fbaa47c717acf89e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "form_submission_values" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "submission_id" integer NOT NULL, "field_key" character varying NOT NULL, "value" text, CONSTRAINT "PK_3d7248b2ca5d134a1566e135164" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."form_submissions_status_enum" AS ENUM('pending', 'approved', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "form_submissions" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "form_id" integer NOT NULL, "user_id" integer, "status" "public"."form_submissions_status_enum" NOT NULL DEFAULT 'pending', CONSTRAINT "PK_fb6e1e9f26cda31c358a8a1530e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."forms_status_enum" AS ENUM('draft', 'published', 'closed')`);
        await queryRunner.query(`CREATE TABLE "forms" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "title" character varying NOT NULL, "slug" character varying NOT NULL, "description" text, "status" "public"."forms_status_enum" NOT NULL DEFAULT 'draft', CONSTRAINT "UQ_beb11480ce7ba6813fe893723a1" UNIQUE ("slug"), CONSTRAINT "PK_ba062fd30b06814a60756f233da" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_attributes" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "product_id" integer NOT NULL, "key" character varying NOT NULL, "value" character varying NOT NULL, CONSTRAINT "PK_4fa18fc5c893cb9894fc40ca921" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_media" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "product_id" integer NOT NULL, "media_id" integer NOT NULL, "is_main" boolean NOT NULL DEFAULT false, "sort_order" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_09d4639de8082a32aa27f3ac9a6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."products_status_enum" AS ENUM('draft', 'active', 'inactive')`);
        await queryRunner.query(`CREATE TABLE "products" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "code" character varying NOT NULL, "title" character varying NOT NULL, "slug" character varying NOT NULL, "description" text, "status" "public"."products_status_enum" NOT NULL DEFAULT 'draft', "views_count" integer NOT NULL DEFAULT '0', CONSTRAINT "UQ_464f927ae360106b783ed0b4106" UNIQUE ("slug"), CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ranks" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "title" character varying NOT NULL, "level" integer NOT NULL, CONSTRAINT "PK_7620a297228c6e9ed28e9fd07e4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "people_sections" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "person_id" integer NOT NULL, "title" character varying NOT NULL, "content" text NOT NULL, "order_index" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_b1872c59cf526f9c00c4c4e4b6f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "people" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "user_id" integer, "picture_id" integer, "full_name" character varying, "rank_id" integer, CONSTRAINT "PK_aa866e71353ee94c6cc51059c5b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."agent_users_role_in_agent_enum" AS ENUM('owner', 'manager', 'staff')`);
        await queryRunner.query(`CREATE TABLE "agent_users" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "user_id" integer NOT NULL, "agent_id" integer NOT NULL, "role_in_agent" "public"."agent_users_role_in_agent_enum" NOT NULL DEFAULT 'staff', CONSTRAINT "UQ_5621a332474df4bf6199aa07d0b" UNIQUE ("user_id", "agent_id"), CONSTRAINT "PK_0c1eef4e643457c2c762c98d557" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."agents_status_enum" AS ENUM('active', 'inactive', 'suspended')`);
        await queryRunner.query(`CREATE TABLE "agents" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "type" character varying NOT NULL, "name" character varying NOT NULL, "company_name" character varying, "phone" character varying NOT NULL, "email" character varying, "address" character varying, "latitude" numeric, "longitude" numeric, "status" "public"."agents_status_enum" NOT NULL DEFAULT 'active', CONSTRAINT "PK_9c653f28ae19c5884d5baf6a1d9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("role_id" integer NOT NULL, "permission_id" integer NOT NULL, CONSTRAINT "PK_25d24010f53bb80b78e412c9656" PRIMARY KEY ("role_id", "permission_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_178199805b901ccd220ab7740e" ON "role_permissions"  ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_17022daf3f885f7d35423e9971" ON "role_permissions"  ("permission_id") `);
        await queryRunner.query(`CREATE TABLE "user_roles" ("user_id" integer NOT NULL, "role_id" integer NOT NULL, CONSTRAINT "PK_23ed6f04fe43066df08379fd034" PRIMARY KEY ("user_id", "role_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_87b8888186ca9769c960e92687" ON "user_roles"  ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b23c65e50a758245a33ee35fda" ON "user_roles"  ("role_id") `);
        await queryRunner.query(`CREATE TABLE "content_categories" ("content_id" integer NOT NULL, "category_id" integer NOT NULL, CONSTRAINT "PK_e886a072525b39097739ca2de41" PRIMARY KEY ("content_id", "category_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_16a1907a253c40298b0a8d11a4" ON "content_categories"  ("content_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_249f24bd45939191ca2dd7ef36" ON "content_categories"  ("category_id") `);
        await queryRunner.query(`CREATE TABLE "content_tags" ("content_id" integer NOT NULL, "tag_id" integer NOT NULL, CONSTRAINT "PK_704201a473cfe0e2f646bea32b3" PRIMARY KEY ("content_id", "tag_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b957bee53dd842e59e479e9afd" ON "content_tags"  ("content_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2346c63b132eacb6cf5a8ccaac" ON "content_tags"  ("tag_id") `);
        await queryRunner.query(`ALTER TABLE "media_relations" ADD CONSTRAINT "FK_4ba5a5a57a2419210a8d9ed2e65" FOREIGN KEY ("media_id") REFERENCES "media"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_96d6f1aafc327443850f263cd50" FOREIGN KEY ("profile_image_id") REFERENCES "media"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "security_logs" ADD CONSTRAINT "FK_3fc41b4fda367506672e9030ad0" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "categories" ADD CONSTRAINT "FK_88cea2dc9c31951d06437879b40" FOREIGN KEY ("parent_id") REFERENCES "categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_4a8e07ff918d47d14b989d0766e" FOREIGN KEY ("content_id") REFERENCES "contents"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_4c675567d2a58f0b07cef09c13d" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_d6f93329801a93536da4241e386" FOREIGN KEY ("parent_id") REFERENCES "comments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ratings" ADD CONSTRAINT "FK_09482ab8d30ebed8df36fb76559" FOREIGN KEY ("content_id") REFERENCES "contents"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ratings" ADD CONSTRAINT "FK_f49ef8d0914a14decddbb170f2f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "content_reports" ADD CONSTRAINT "FK_355c7f8b132e5df78682ca52de0" FOREIGN KEY ("content_id") REFERENCES "contents"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "content_reports" ADD CONSTRAINT "FK_5780f25ece1e67bdb760b534115" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contents" ADD CONSTRAINT "FK_4115a736908fc57053cb83da0b2" FOREIGN KEY ("cover_id") REFERENCES "media"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contents" ADD CONSTRAINT "FK_ef9aa2f7890c5652724605b6724" FOREIGN KEY ("author_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_fields" ADD CONSTRAINT "FK_c2076d2b47add1aaa07608e0cf2" FOREIGN KEY ("form_id") REFERENCES "forms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_permissions" ADD CONSTRAINT "FK_6aa067c0cb1dc7a3741f58f3dcb" FOREIGN KEY ("form_id") REFERENCES "forms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_permissions" ADD CONSTRAINT "FK_7e1b2ed0f4bec4fec75e918d46b" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_submission_values" ADD CONSTRAINT "FK_f8033df1f0e2b48ec2ff40e24d7" FOREIGN KEY ("submission_id") REFERENCES "form_submissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_submissions" ADD CONSTRAINT "FK_56176b21d723c3b3344305c48e1" FOREIGN KEY ("form_id") REFERENCES "forms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_submissions" ADD CONSTRAINT "FK_e640f81eb076cc88ca6bf28820e" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_attributes" ADD CONSTRAINT "FK_f5a6700abd0494bae3032cf5bbd" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_media" ADD CONSTRAINT "FK_e6bb4a69096db4f6a1f5bada151" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_media" ADD CONSTRAINT "FK_b0895b1d84d747625a54b7fe9cf" FOREIGN KEY ("media_id") REFERENCES "media"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "people_sections" ADD CONSTRAINT "FK_65f277f10d6eddc8dc5e0d93300" FOREIGN KEY ("person_id") REFERENCES "people"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "people" ADD CONSTRAINT "FK_e2bceeacac0dd5be3d8c37b068c" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "people" ADD CONSTRAINT "FK_79ca070107e4c5fca68187f5efd" FOREIGN KEY ("picture_id") REFERENCES "media"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "people" ADD CONSTRAINT "FK_e2eb2b0f1fea451ca8f21e2e430" FOREIGN KEY ("rank_id") REFERENCES "ranks"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agent_users" ADD CONSTRAINT "FK_a5411e6cd30789dc03c5ec6900f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agent_users" ADD CONSTRAINT "FK_8f552cb8ba155ca708796c70d4f" FOREIGN KEY ("agent_id") REFERENCES "agents"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_87b8888186ca9769c960e926870" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_b23c65e50a758245a33ee35fda1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "content_categories" ADD CONSTRAINT "FK_16a1907a253c40298b0a8d11a42" FOREIGN KEY ("content_id") REFERENCES "contents"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "content_categories" ADD CONSTRAINT "FK_249f24bd45939191ca2dd7ef36a" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "content_tags" ADD CONSTRAINT "FK_b957bee53dd842e59e479e9afde" FOREIGN KEY ("content_id") REFERENCES "contents"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "content_tags" ADD CONSTRAINT "FK_2346c63b132eacb6cf5a8ccaacd" FOREIGN KEY ("tag_id") REFERENCES "tags"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "content_tags" DROP CONSTRAINT "FK_2346c63b132eacb6cf5a8ccaacd"`);
        await queryRunner.query(`ALTER TABLE "content_tags" DROP CONSTRAINT "FK_b957bee53dd842e59e479e9afde"`);
        await queryRunner.query(`ALTER TABLE "content_categories" DROP CONSTRAINT "FK_249f24bd45939191ca2dd7ef36a"`);
        await queryRunner.query(`ALTER TABLE "content_categories" DROP CONSTRAINT "FK_16a1907a253c40298b0a8d11a42"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_b23c65e50a758245a33ee35fda1"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_87b8888186ca9769c960e926870"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "agent_users" DROP CONSTRAINT "FK_8f552cb8ba155ca708796c70d4f"`);
        await queryRunner.query(`ALTER TABLE "agent_users" DROP CONSTRAINT "FK_a5411e6cd30789dc03c5ec6900f"`);
        await queryRunner.query(`ALTER TABLE "people" DROP CONSTRAINT "FK_e2eb2b0f1fea451ca8f21e2e430"`);
        await queryRunner.query(`ALTER TABLE "people" DROP CONSTRAINT "FK_79ca070107e4c5fca68187f5efd"`);
        await queryRunner.query(`ALTER TABLE "people" DROP CONSTRAINT "FK_e2bceeacac0dd5be3d8c37b068c"`);
        await queryRunner.query(`ALTER TABLE "people_sections" DROP CONSTRAINT "FK_65f277f10d6eddc8dc5e0d93300"`);
        await queryRunner.query(`ALTER TABLE "product_media" DROP CONSTRAINT "FK_b0895b1d84d747625a54b7fe9cf"`);
        await queryRunner.query(`ALTER TABLE "product_media" DROP CONSTRAINT "FK_e6bb4a69096db4f6a1f5bada151"`);
        await queryRunner.query(`ALTER TABLE "product_attributes" DROP CONSTRAINT "FK_f5a6700abd0494bae3032cf5bbd"`);
        await queryRunner.query(`ALTER TABLE "form_submissions" DROP CONSTRAINT "FK_e640f81eb076cc88ca6bf28820e"`);
        await queryRunner.query(`ALTER TABLE "form_submissions" DROP CONSTRAINT "FK_56176b21d723c3b3344305c48e1"`);
        await queryRunner.query(`ALTER TABLE "form_submission_values" DROP CONSTRAINT "FK_f8033df1f0e2b48ec2ff40e24d7"`);
        await queryRunner.query(`ALTER TABLE "form_permissions" DROP CONSTRAINT "FK_7e1b2ed0f4bec4fec75e918d46b"`);
        await queryRunner.query(`ALTER TABLE "form_permissions" DROP CONSTRAINT "FK_6aa067c0cb1dc7a3741f58f3dcb"`);
        await queryRunner.query(`ALTER TABLE "form_fields" DROP CONSTRAINT "FK_c2076d2b47add1aaa07608e0cf2"`);
        await queryRunner.query(`ALTER TABLE "contents" DROP CONSTRAINT "FK_ef9aa2f7890c5652724605b6724"`);
        await queryRunner.query(`ALTER TABLE "contents" DROP CONSTRAINT "FK_4115a736908fc57053cb83da0b2"`);
        await queryRunner.query(`ALTER TABLE "content_reports" DROP CONSTRAINT "FK_5780f25ece1e67bdb760b534115"`);
        await queryRunner.query(`ALTER TABLE "content_reports" DROP CONSTRAINT "FK_355c7f8b132e5df78682ca52de0"`);
        await queryRunner.query(`ALTER TABLE "ratings" DROP CONSTRAINT "FK_f49ef8d0914a14decddbb170f2f"`);
        await queryRunner.query(`ALTER TABLE "ratings" DROP CONSTRAINT "FK_09482ab8d30ebed8df36fb76559"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_d6f93329801a93536da4241e386"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_4c675567d2a58f0b07cef09c13d"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_4a8e07ff918d47d14b989d0766e"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP CONSTRAINT "FK_88cea2dc9c31951d06437879b40"`);
        await queryRunner.query(`ALTER TABLE "security_logs" DROP CONSTRAINT "FK_3fc41b4fda367506672e9030ad0"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_96d6f1aafc327443850f263cd50"`);
        await queryRunner.query(`ALTER TABLE "media_relations" DROP CONSTRAINT "FK_4ba5a5a57a2419210a8d9ed2e65"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2346c63b132eacb6cf5a8ccaac"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b957bee53dd842e59e479e9afd"`);
        await queryRunner.query(`DROP TABLE "content_tags"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_249f24bd45939191ca2dd7ef36"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_16a1907a253c40298b0a8d11a4"`);
        await queryRunner.query(`DROP TABLE "content_categories"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b23c65e50a758245a33ee35fda"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_87b8888186ca9769c960e92687"`);
        await queryRunner.query(`DROP TABLE "user_roles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_17022daf3f885f7d35423e9971"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_178199805b901ccd220ab7740e"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP TABLE "agents"`);
        await queryRunner.query(`DROP TYPE "public"."agents_status_enum"`);
        await queryRunner.query(`DROP TABLE "agent_users"`);
        await queryRunner.query(`DROP TYPE "public"."agent_users_role_in_agent_enum"`);
        await queryRunner.query(`DROP TABLE "people"`);
        await queryRunner.query(`DROP TABLE "people_sections"`);
        await queryRunner.query(`DROP TABLE "ranks"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP TYPE "public"."products_status_enum"`);
        await queryRunner.query(`DROP TABLE "product_media"`);
        await queryRunner.query(`DROP TABLE "product_attributes"`);
        await queryRunner.query(`DROP TABLE "forms"`);
        await queryRunner.query(`DROP TYPE "public"."forms_status_enum"`);
        await queryRunner.query(`DROP TABLE "form_submissions"`);
        await queryRunner.query(`DROP TYPE "public"."form_submissions_status_enum"`);
        await queryRunner.query(`DROP TABLE "form_submission_values"`);
        await queryRunner.query(`DROP TABLE "form_permissions"`);
        await queryRunner.query(`DROP TABLE "form_fields"`);
        await queryRunner.query(`DROP TYPE "public"."form_fields_type_enum"`);
        await queryRunner.query(`DROP TABLE "contents"`);
        await queryRunner.query(`DROP TYPE "public"."contents_status_enum"`);
        await queryRunner.query(`DROP TABLE "content_reports"`);
        await queryRunner.query(`DROP TYPE "public"."content_reports_status_enum"`);
        await queryRunner.query(`DROP TABLE "ratings"`);
        await queryRunner.query(`DROP TABLE "comments"`);
        await queryRunner.query(`DROP TYPE "public"."comments_status_enum"`);
        await queryRunner.query(`DROP TABLE "tags"`);
        await queryRunner.query(`DROP TABLE "categories"`);
        await queryRunner.query(`DROP TABLE "system_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3fc41b4fda367506672e9030ad"`);
        await queryRunner.query(`DROP TABLE "security_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bd2726fd31b35443f2245b93ba"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7421efc125d95e413657efa3c6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cee5459245f652b75eb2759b4c"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TABLE "otp_codes"`);
        await queryRunner.query(`DROP TYPE "public"."otp_codes_purpose_enum"`);
        await queryRunner.query(`DROP TABLE "blocked_ips"`);
        await queryRunner.query(`DROP TYPE "public"."blocked_ips_reason_enum"`);
        await queryRunner.query(`DROP INDEX "public"."users_verified_email_unique"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP TABLE "media"`);
        await queryRunner.query(`DROP TABLE "media_relations"`);
    }

}
